bliss_ignored: true
celery:
  accept_content:
  - application/json
  - application/x-python-serialize
  broker_url: redis://localhost:6379/3
  result_backend: redis://localhost:6379/4
  result_expires: 600
  result_serializer: pickle
  task_remote_tracebacks: true
  broker_connection_retry_on_startup: true
  enable_utc: false
ewoks_execution:
  execinfo:
    handlers:
      - class: "ewoksjob.events.handlers.RedisEwoksEventHandler"
        arguments:
          - name: "url"
            value: "redis://localhost:6379/2"
