name: Release

on:
  workflow_dispatch:

jobs:
  # Build Python package
  build:
    uses: ewoks-kit/.github/.github/workflows/python-build.yml@main

  # Run tests
  tests:
    needs: build
    uses: ewoks-kit/.github/.github/workflows/python-tests.yml@main
    with:
      qt-api: PyQt6
      pytest-args: >-
        -v -ra -W error
        -W ignore::DeprecationWarning:kombu.utils.compat
        -W ignore::DeprecationWarning:celery.utils.imports
        -W ignore::DeprecationWarning:kombu.transport.redis
        -W ignore::pydantic.warnings.PydanticDeprecatedSince20
        -W ignore::RuntimeWarning:networkx.utils.backends

  # Publish package to TestPyPI
  publish-testpypi:
    needs: tests
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: ewoks-kit/.github/.github/actions/setup-python-package@main
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  # Publish package to PyPI
  publish-pypi:
    needs: tests
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: ewoks-kit/.github/.github/actions/setup-python-package@main
      - uses: pypa/gh-action-pypi-publish@release/v1

  # Tag
  tag-release:
    needs: publish-pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: ewoks-kit/.github/.github/actions/setup-python-package@main
      - uses: ewoks-kit/.github/.github/actions/tag-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
